XENUS_IMPORT l_int __mnt_is_readonly(vfsmount_k mnt);
XENUS_IMPORT l_int mnt_want_write(vfsmount_k m);
XENUS_IMPORT l_int mnt_clone_write(vfsmount_k mnt);
XENUS_IMPORT l_int mnt_want_write_file(file_k file);
XENUS_IMPORT void mnt_drop_write(vfsmount_k mnt);
XENUS_IMPORT void mnt_drop_write_file(file_k file);
XENUS_IMPORT vfsmount_k vfs_kern_mount(file_system_type_k type, l_int flags, const char * name, void * data);
XENUS_IMPORT vfsmount_k vfs_submount(const dentry_k mountpoint, file_system_type_k type, const char * name, void * data);
XENUS_IMPORT void mntput(vfsmount_k mnt);
XENUS_IMPORT vfsmount_k mntget(vfsmount_k mnt);
XENUS_IMPORT bool path_is_mountpoint(const path_k path);
XENUS_IMPORT l_int may_umount_tree(vfsmount_k m);
XENUS_IMPORT l_int may_umount(vfsmount_k mnt);
XENUS_IMPORT vfsmount_k clone_private_mount(const path_k path);
XENUS_IMPORT void mnt_set_expiry(vfsmount_k mnt, list_head_k expiry_list);
XENUS_IMPORT void mark_mounts_for_expiry(list_head_k mounts);
XENUS_IMPORT dentry_k mount_subtree(vfsmount_k mnt, const char * name);
XENUS_IMPORT bool path_is_under(const path_k path1, const path_k path2);
XENUS_IMPORT vfsmount_k kern_mount_data(file_system_type_k type, void * data);
XENUS_IMPORT void kern_unmount(vfsmount_k mnt);
