XENUS_IMPORT l_int set_cpus_allowed_ptr(task_k p, const cpumask_k new_mask);
XENUS_IMPORT void kick_process(task_k p);
XENUS_IMPORT l_int wake_up_process(task_k p);
XENUS_IMPORT void preempt_notifier_inc();
XENUS_IMPORT void preempt_notifier_dec();
XENUS_IMPORT void preempt_notifier_register(preempt_notifier_k notifier);
XENUS_IMPORT void preempt_notifier_unregister(preempt_notifier_k notifier);
XENUS_IMPORT bool single_task_running();
XENUS_IMPORT void preempt_count_add(l_int val);
XENUS_IMPORT void preempt_count_sub(l_int val);
XENUS_IMPORT void schedule();
XENUS_IMPORT void preempt_schedule();
XENUS_IMPORT void preempt_schedule_notrace();
XENUS_IMPORT l_int default_wake_function(wait_queue_entry_t_p curr, l_unsigned mode, l_int wake_flags, void * data);
XENUS_IMPORT void set_user_nice(task_k p, l_long nice);
XENUS_IMPORT l_int sched_setscheduler(task_k p, l_int policy, const sched_param_k param);
XENUS_IMPORT l_int sched_setattr(task_k p, const sched_attr_k attr);
XENUS_IMPORT l_int sched_setscheduler_nocheck(task_k p, l_int policy, const sched_param_k param);
XENUS_IMPORT l_int  _cond_resched();
XENUS_IMPORT l_int  __cond_resched_softirq();
XENUS_IMPORT void  yield();
XENUS_IMPORT l_int  yield_to(task_k p, bool preempt);
XENUS_IMPORT l_long  io_schedule_timeout(l_long timeout);
XENUS_IMPORT void io_schedule();
XENUS_IMPORT void __might_sleep(const char * file, l_int line, l_int preempt_offset);
XENUS_IMPORT void ___might_sleep(const char * file, l_int line, l_int preempt_offset);
